on:
  push:

jobs:
  check-version:
    runs-on: ubuntu-latest
    container: 
      image: cassandra:3.11
    steps:
      # Simple command to check Cassandra version
      - name: Check Cassandra version
        run: |
          cassandra -v