on: push

jobs:
  build-cassandra:
    runs-on: ubuntu-latest
    container:
      image: cassandra:3.11
    steps:
      - name: Check cqlsh version
        run: cqlsh --version
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Wait for Cassandra to start
        run: |
          for i in {1..30}; do
            if cqlsh -e "SELECT now() FROM system.local" > /dev/null 2>&1; then
              echo "Cassandra is up and running"
              break
            fi
            echo "Waiting for Cassandra..."
            sleep 5
          done
      - name: Create keyspace
        run: 'cqlsh -e "CREATE KEYSPACE test WITH replication = {''class'': ''SimpleStrategy'', ''replication_factor'': 1};"'
      - name: Create table
        run: 'cqlsh -e "CREATE TABLE test.users (id int PRIMARY KEY, name text);"'
      - name: Insert data
        run: 'cqlsh -e "INSERT INTO test.users (id, name) VALUES (1, ''John'');"'
      - name: Select data
        run: 'cqlsh -e "SELECT * FROM test.users;"'
